CREATE TABLE covid_chile.covid_data (
    "AÑO" INT NOT NULL,
    "FECHA_DEF" DATE NOT NULL,
    "SEXO_NOMBRE" VARCHAR(10) NOT NULL,
    "EDAD_CANT" INT NOT NULL,
    "COMUNA" VARCHAR(100) NOT NULL,
    "NOMBRE_REGION" VARCHAR(100) NOT NULL,
    "LUGAR_DEFUNCION" VARCHAR(100) NOT NULL,
    "PERIODO" VARCHAR(7) NOT NULL,
    "RANGO_ETARIO" VARCHAR(20) NOT NULL
);